### ISSUE TITLE
Have to redo the "registration" everytime a player reconnects to the server.

### ISSUE THREAD

**Issue by antonklang** [ESX-Org/esx_identity#17]
Like the title says, everytime someone tries to connect to the server they have to refill their First name / surname / Age / Gender / Height. Even tho its not their first time joining.

For some reason its like the character doesnt save for anyone and they have to redo everything. Still they have the same phone number / contacts and inventory. Everything works execpt that u have to refill the registration menu everytime you try to connect.

Sorry for my bad English im a foreign.

**Comment by eagledude4** [comment]
You probably didn't run both sql scripts
