### ISSUE TITLE
esx_identity error

### ISSUE THREAD

**Issue by dylan48700** [ESX-Org/esx_identity#22]
Hello, I have a problem with esx_identity.
I have the colone and the table in my database but in the game, I register, I leave, I come back, and my info is not saved I must start at each connection. besides, I have an error in the log:

#
Could someone please help me ?
![erreur](https://user-images.githubusercontent.com/32740071/41999848-276b069e-7a5f-11e8-9fb9-4795fced126f.JPG)

Thank you very much

**Comment by donnes** [comment]
Facing the same issue

**Comment by ColeT3tr3x** [comment]
Same here.
