### ISSUE TITLE
SQL error Unknown column 'is_dead' in 'field list' 

### ISSUE THREAD

**Issue by itsjeroentje** [ESX-Org/esx_identity#28]
When a player join my server i get a error in my console that is saying:  [ERROR] [MySQL] An error happens on MySQL for query "SELECT is_dead FROM users WHERE identifier = @identifier {@identifier=steam:XXXXXXXXXXX}": Unknown column 'is_dead' in 'field list'. I dont know how to fix this

**Comment by ElPumpo** [comment]
not this resource

**Comment by MrAdapt** [comment]
Sorry to necro this, but i get this same issue can't seem to find a fix for it
