### ISSUE TITLE
"Player not online"

### ISSUE THREAD

**Issue by OJits** [ESX-Org/esx_identity#33]
So i had an identity script that relaced this one and I was having issues with that one so i reverted back to esx_identity . Removed the whole folder (esx_identity) and installed it again. and now whenever i go and /setjob it says "player is not online" 
Not sure what to do, it did this before but i forgot how i fixed it.

**Comment by Jay187erz** [comment]
I have the same problem please help me

**Comment by James1532** [comment]
same

**Comment by Cyze** [comment]
i neeed Helpp
