### ISSUE TITLE
Error esx_identity 

### ISSUE THREAD

**Issue by GewoonMarlon** [ESX-Org/esx_identity#35]
When i create my charatcter i get an error in the console : 

[ERROR] [MySQL] [esx_identity] An error happens on MySQL for query "[object Object]": ER_BAD_NULL_ERROR: Column 'identifier' cannot be null

How do i solve this problem

**Comment by Kamer5555** [comment]
You haven't added a sql file from esx_identity folder to your database.

**Comment by manups4e** [comment]
i'm getting it too both "license" and "identifier" and my sql has always been good.. it happened like 2 weeks ago and since then i couldn't find a fix yet

**Comment by Puyodead1** [comment]
same issue
```[ERROR] [MySQL] [esx_identity] An error happens on MySQL for query "[object Object]": ER_BAD_NULL_ERROR: Column 'identifier' cannot be null
```
