### ISSUE TITLE
Help with Error! esx_identity and es_extended!

### ISSUE THREAD

**Issue by hasmal95** [ESX-Org/esx_identity#39]
this is my server Errors…!!

`Error running call reference function for resource esx_identity: citizen:/scripting/lua/scheduler.lua:403: @esx_identity/server/main.lua:11: attempt to index a nil value (field '?')
stack traceback:
        @esx_identity/server/main.lua:11: in upvalue 'ref'
        citizen:/scripting/lua/scheduler.lua:389: in function <citizen:/scripting/lua/scheduler.lua:388>
        [C]: in function 'xpcall'
        citizen:/scripting/lua/scheduler.lua:388: in function <citizen:/scripting/lua/scheduler.lua:387>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:403: in function <citizen:/scripting/lua/scheduler.lua:372>
Error: Unhandled error in timer: Error: BUFFER_SHORTAGE
Error: BUFFER_SHORTAGE
    at n.e [as reserve] (citizen:/scripting/v8/msgpack.js:29:12766)
    at h (citizen:/scripting/v8/msgpack.js:29:15761)
    at n.r [as decode] (citizen:/scripting/v8/msgpack.js:29:13908)
    at n.fetch (citizen:/scripting/v8/msgpack.js:29:6972)
    at n.u [as read] (citizen:/scripting/v8/msgpack.js:29:12076)
    at Object.n [as decode] (citizen:/scripting/v8/msgpack.js:29:7097)
    at unpack (citizen:/scripting/v8/main.js:20:33)
    at citizen:/scripting/v8/main.js:51:20
    at setImmediate (mysql-async.js:4962:9)
    at Object.callback (citizen:/scripting/v8/timer.js:96:21)
Error running call reference function for resource es_extended: citizen:/scripting/lua/scheduler.lua:403: @es_extended/server/main.lua:133: attempt to index a nil value (field '?')
stack traceback:
        @es_extended/server/main.lua:133: in upvalue 'ref'
        citizen:/scripting/lua/scheduler.lua:389: in function <citizen:/scripting/lua/scheduler.lua:388>
        [C]: in function 'xpcall'
        citizen:/scripting/lua/scheduler.lua:388: in function <citizen:/scripting/lua/scheduler.lua:387>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:403: in function <citizen:/scripting/lua/scheduler.lua:372>
Error: Unhandled error in timer: Error: BUFFER_SHORTAGE
Error: BUFFER_SHORTAGE
    at n.e [as reserve] (citizen:/scripting/v8/msgpack.js:29:12766)
    at h (citizen:/scripting/v8/msgpack.js:29:15761)
    at n.r [as decode] (citizen:/scripting/v8/msgpack.js:29:13908)
    at n.fetch (citizen:/scripting/v8/msgpack.js:29:6972)
    at n.u [as read] (citizen:/scripting/v8/msgpack.js:29:12076)
    at Object.n [as decode] (citizen:/scripting/v8/msgpack.js:29:7097)
    at unpack (citizen:/scripting/v8/main.js:20:33)
    at citizen:/scripting/v8/main.js:51:20
    at setImmediate (mysql-async.js:4962:9)
    at Object.callback (citizen:/scripting/v8/timer.js:96:21)
Error: (node:12804) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at execute.then (mysql-async.js:5002:48)
Error: (node:12804) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
Error: (node:12804) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`
![error 2](https://user-images.githubusercontent.com/49456894/55831919-fd655800-5b1c-11e9-9ac5-9f6721ee58dd.jpg)
![error 3](https://user-images.githubusercontent.com/49456894/55831921-fd655800-5b1c-11e9-9457-5cdb36cc51b6.jpg)

this is my server cfg

![11](https://user-images.githubusercontent.com/49456894/55832579-8a5ce100-5b1e-11e9-9da1-d8d95bca56cb.jpg)
![22](https://user-images.githubusercontent.com/49456894/55832580-8a5ce100-5b1e-11e9-8cee-5bfb21be541d.JPG)
![33](https://user-images.githubusercontent.com/49456894/55832582-8a5ce100-5b1e-11e9-880a-8857fc9fc5fb.JPG)
![44](https://user-images.githubusercontent.com/49456894/55832584-8af57780-5b1e-11e9-9552-8cb3d09f51f2.JPG)

thanks…!!

**Comment by yogiyendri** [comment]
same issue

**Comment by hasmal95** [comment]
i have make new DB 2 times... :/

**Comment by hasmal95** [comment]
> same issue

bro, rebuild your Database!! 
it works for me..!! :)

**Comment by yogiyendri** [comment]
> 
> 
> > same issue
> 
> bro, rebuild your Database!!
> it works for me..!! :)

okay bro, thanks, work for me to :)

**Comment by K3IDB** [comment]
how to rebuild ?
i have some issue too :'(

**Comment by K3IDB** [comment]
already re-built sql but not work :'(
