### ISSUE TITLE
[ERROR] MySQL

### ISSUE THREAD

**Issue by HoogedamRP** [ESX-Org/esx_identity#48]
[ERROR] [MySQL] An error happens on MySQL for query "UPDATE users SET is_dead = @isDead WHERE identifier = @identifier {@isDead=True;@identifier=steam:XXXXXXXXXXXXXXX}": Unknown column 'is_dead' in 'field list'

**Comment by x0Z3ro0x** [comment]
Very simple, you failed to import the proper SQLs when setting up your server.
