### ISSUE TITLE
My chat keeps opening while making a new character with letter T

### ISSUE THREAD

**Issue by Domitresku** [ESX-Org/esx_identity#52]
Anyone knows how to do that ? i thought it will automaticly disable opening chat

**Comment by tfurci** [comment]
hi i have the same problem. Did you found the solution?

**Comment by Domitresku** [comment]
> hi i have the same problem. Did you found the solution?

Hello, no, i didn't find any solutions yet. I'll catch up with you when i find the solution.

**Comment by tfurci** [comment]
In meantime i found the solution(it works for me) in esx_identity/client/main.lua there are lines with DisableControlAction and then i added the line DisableControlAction with number 245 like DisableControlAction(0, 245,  true) -- Chat because 245 stand for default keybind for chat. If its gonna work for you let me know.

**Comment by Domitresku** [comment]
> In meantime i found the solution(it works for me) in esx_identity/client/main.lua there are lines with DisableControlAction and then i added the line DisableControlAction with number 245 like DisableControlAction(0, 245, true) because 245 stand for default keybind for chat. If its gonna work for you let me know.

Thanks so much for solving this problem, send me your discord, i'll mention you on my server for help :-)

**Comment by tfurci** [comment]
I'm glad that i helped you. My discord is TfourJ#4391

**Comment by dwiprizzy** [comment]
still getting bug hmm

**Comment by Patrickstek121** [comment]
But no one can make a name now witch a T?

**Comment by CALauer** [comment]
Read my posts

**Comment by CALauer** [comment]
Move < 		Citizen.Wait(10)  <<<<<<<<<<<<<<<
To above line: if guiEnabled then 
    DisableControlAction()blah blah blah 
and change from 10 to 0

Should look like this 	
	Citizen.Wait(0)
		if guiEnabled then
			DisableControlAction(0, 1,   true) -- LookLeftRight
			DisableControlAction(0, 2,   true) -- LookUpDown

**Comment by snakezdigital** [comment]
> Move < Citizen.Wait(10) <<<<<<<<<<<<<<<
> To above line: if guiEnabled then
> DisableControlAction()blah blah blah
> and change from 10 to 0
> 
> Should look like this
> Citizen.Wait(0)
> if guiEnabled then
> DisableControlAction(0, 1, true) -- LookLeftRight
> DisableControlAction(0, 2, true) -- LookUpDown

I tried but still doesnt work the strange thing is that if you write /register again the character is freeze and you can use keyboard and mouse, this problem is just for the first spawn. We need to find a solution

**Comment by CALauer** [comment]
This is what it should look like:

Citizen.CreateThread(function()
	while true do
		Citizen.Wait(0)
		if guiEnabled then
			DisableControlAction(0, 1,   true) -- LookLeftRight
			DisableControlAction(0, 2,   true) -- LookUpDown
			DisableControlAction(0, 106, true) -- VehicleMouseControlOverride
			DisableControlAction(0, 142, true) -- MeleeAttackAlternate
			DisableControlAction(0, 30,  true) -- MoveLeftRight
			DisableControlAction(0, 31,  true) -- MoveUpDown
			DisableControlAction(0, 21,  true) -- disable sprint
			DisableControlAction(0, 24,  true) -- disable attack
			DisableControlAction(0, 25,  true) -- disable aim
			DisableControlAction(0, 47,  true) -- disable weapon
			DisableControlAction(0, 58,  true) -- disable weapon
			DisableControlAction(0, 263, true) -- disable melee
			DisableControlAction(0, 264, true) -- disable melee
			DisableControlAction(0, 257, true) -- disable melee
			DisableControlAction(0, 140, true) -- disable melee
			DisableControlAction(0, 141, true) -- disable melee
			DisableControlAction(0, 143, true) -- disable melee
			DisableControlAction(0, 75,  true) -- disable exit vehicle
			DisableControlAction(27, 75, true) -- disable exit vehicle
		end

	end
end)

**Comment by snakezdigital** [comment]
i tried it but after some seconds the mouse icon disapper and its bugging
