### ISSUE TITLE
Register form doesn't open

### ISSUE THREAD

**Issue by PluginYML** [ESX-Org/esx_identity#53]
Hi,

when I go to my server, the registration form does not open ..

Startup:
# These resources will start by default.
start mapmanager
start chat
start spawnmanager
start fivem
start hardcap
start rconlog
start playernames

#FIX ERRORS
restart sessionmanager

#util
start loadingscreen
start coords
start async
start cron
start skinchanger
start reducednpcs
start noplayerblips
start nonpcdrop
start interiorfix

#mysql
start mysql-async

#essential
start essentialmode
start esplugin_mysql
start es_admin
start es_extended
start esx_skin
start esx_identity
start esx_menu_default
start esx_menu_list
start esx_menu_dialog
start esx_status
start esx_basicneeds
start esx_addonaccount
start esx_addoninventory
start esx_billing
start esx_society
start esx_vehicleshop
start esx_license
start esx_datastore
start esx_policejob

#chat

**Comment by ColeT3tr3x** [comment]
Same here...

**Comment by rheein** [comment]
Same here (2)...

**Comment by ShiftyOG** [comment]
Interesting this has just started happening to me

**Comment by EbenSantuy** [comment]
Same here... (3)

**Comment by Zasty** [comment]
change name folder ESX to esx
