### ISSUE TITLE
joining error

### ISSUE THREAD

**Issue by Hawknationdev** [ESX-Org/esx_identity#54]
When i'm joined on the Server came this error 

SCRIPT ERROR: @esx_identity/server/main.lua:11: attempt to index a nil value (field '?')
> ref (@esx_identity/server/main.lua:11)
>  (@mysql-async/mysql-async.js:14959)

PS: i´m have on this Server all new from ESX Framework and Requirements

**Comment by Hawknationdev** [comment]
i´m have on this Server all new from ESX Framework and Requirements

**Comment by nessx** [comment]
check that in the database, there is no empty field in the users table. :)
