### ISSUE TITLE
cant fix this issue

### ISSUE THREAD

**Issue by railroadnl** [ESX-Org/esx_identity#57]
I have installed ESX identity and other   ESX Files that was needed, but when im starting the server 
Everything is fine.
But when i Joining the server, No identity came up  or something, 

In the server i see This fail:
```
SCRIPT ERROR: @esx_identity/server.lua:23: attempt to index a nil value (field '?')
> ref (@esx_identity/server.lua:23)
>  (@mysql-async/mysql-async.js:14431)
```

i have tried to replace it with a new one but nothing  hapens.

I dont know animore where to look

Maybe is it verry simple maybe not :D

**Comment by wokieman** [comment]
same for me
