### ISSUE TITLE
Invisible character

### ISSUE THREAD

**Issue by MJRamon** [ESX-Org/esx_identity#7]
After completing registration form, triggers
`TriggerEvent('esx_skin:openSaveableMenu')`

Except this method doesn't load default model, so player is invisible. You can press enter and stay invisible.

**Comment by ArkSeyonet** [comment]
I will check into this.

**Comment by Hovra** [comment]
Still have this problem

**Comment by ElPumpo** [comment]
Shouldn't happen. Reopen if this issue persists

**Comment by AjaxTheGod** [comment]
I'm having this issue now too. It's specific to certain people where they will be invisible for other players and every other player will be invisible to them too.
