### ISSUE TITLE
Using ID for whitelisting

### ISSUE THREAD

**Issue by deathjdstn** [ESX-Org/esx_identity#8]
For white listed jobs this could help solve this issue.

Let me explain:

If cops on a server is whitelisted only, this means only server admins/cop boss can place someone on duty for a cop.

Lets say this player wants to go off duty and do mining for awhile, he cannot as he would no longer be a cop and has no way to go back on duty. If we can get something with in the ID system to allow this so when for example they switch to character 2 they can switch jobs and does not effect character 1 and character 1 is still a cop when he switches back.

Do you think this is something we can do?

Thanks

**Comment by ArkSeyonet** [comment]
This would require edits to most of ESX itself, because all of that information is tied to the steamidentifier. It would be a decision that the creators of ESX would have to decide upon, not myself. I just made the script to support ESX.

**Comment by ElPumpo** [comment]
Requires a lot of changes and in the end isn't worth it. I understand e.g have the policejob but want different profiles, but it'll require a lot of changes to the core.
