### ISSUE TITLE
Skin not tied to character

### ISSUE THREAD

**Issue by deathjdstn** [ESX-Org/esx_identity#9]
Clothing and skins is staying between characters, meaning that what ever skin or cloths I choose it does not save each character does not load the cloths i choose for that other character

**Comment by ArkSeyonet** [comment]
This would require edits to most of ESX itself, because all of that information is tied to the steamidentifier. It would be a decision that the creators of ESX would have to decide upon, not myself. I just made the script to support ESX.

**Comment by CombatVG** [comment]
what if we tied that character skin to the characters table and pulled that information with the character.
