### ISSUE TITLE
Duplicate Column Name 'firstname'

### ISSUE THREAD

**Issue by Source911** [ESX-Org/esx_identity#91]
![image](https://user-images.githubusercontent.com/40721856/81766876-00134900-94a5-11ea-83c8-797bc0a6a6a9.png)
Im not sure what the issue is here

**Comment by ElDuckyy** [comment]
look at sql file see what table it edits then goto that table usually its users and make sure first name is not a column
 in there

**Comment by Source911** [comment]
I just restarted my computer and it somehow fixed it gotta love it
